config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'
  devise_for :users

  resources :issues, only: [:index, :show, :new, :create, :destroy, :edit, :update]
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :user
  validates :headline, presence: true

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  after_validation :geocode, if: :address_changed?
  after_validation :reverse_geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :issues
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << [
      :email,
      :username,
      :phone_number,
      :emergency_contact,
      :emergency_contact_phone,
      :emergency_contact_email
  ]

  devise_parameter_sanitizer.for(:account_update) << [
    :email,
    :username,
    :phone_number,
    :emergency_contact,
    :emergency_contact_phone,
    :emergency_contact_email
  ]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  respond_to :html, :js

  def index
    @issues = Issue.all
    @not_completed_issues = []
    @issues.each do |issue|
      if !issue.completed?
        @not_completed_issues << issue
      end
    end
    respond_to do |format|
      format.html
      format.json { render json: @not_completed_issues }
    end
  end

  def show
  	@issue = Issue.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @issue }
    end
  end

  def new
		@issue = Issue.new
  end

	def create
  	@issue = Issue.new(issue_params)

		if @issue.save
      # IssueMailer.issue_notification(@issue, @program.user).deliver_later
      respond_to do |format|
        format.html do
    			flash[:notice] = "Issue Successfully Added!"
    			redirect_to root_path
        end
        format.json { render json: { status: 200 } }
      end
		else
      respond_to do |format|
        format.html do
          flash[:notice] = @issue.errors.full_messages.join(". ")
          redirect_to new_issue_path
        end
        format.json { render json: { status: 500 } }
      end
		end
	end

  def destroy
    if current_user.try(:admin?)
      @issue = Issue.find(params[:id])
      @issue.destroy
      flash[:notice] = 'Issue deleted.'
      redirect_to root_path
    else
      redirect_to root_path
      flash[:notice] = "Only admins can delete submissions!"
    end
  end

  def update
    @issue = Issue.find(params[:id])

    if @issue.update(issue_params)
      flash[:notice] = "Issue Edited"
      redirect_to root_path
    else
      flash[:notice] = @issue.errors.full_messages.join(". ")
      redirect_to edit_issue_path(@issue)
    end
  end

  def edit
    if current_user.try(:admin?)
      @issue = Issue.find(params[:id])
    else
      flash[:notice] = "This portion of the site is for admins only!"
      redirect_to root_path
    end
  end

  protected

  def issue_params
    params.require(:issue).permit(:description, :headline, :longitude,
      :latitude, :completed, :address)
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/issues/edit.html.erb
<h4>Edit <%= @issue.headline %></h4>

<%= form_for @issue do |f| %>

    <%= f.label "headline" %><br>
    <%= f.text_field :headline %>

    <%= f.label "description" %><br>
    <%= f.text_field :description %>

    <%= f.submit "Edit Issue" %>

<% end %>

app/views/issues/index.html.erb
<div class="panel" id="map"></div>

   <div class="submit-issue-div">
     <%= button_to "Submit New Issue", new_issue_path, method: :get, class: "submit-issue" %>
   </div>

<div class="background-shader large-2 large-offset-5 small-6 small-offset-3 columns text-center">
  <div class="issue-list-title" id="issue-list-title">Issue List</div>
</div>

<br>
<div class="row hide">

   <div class="small-9 large-12 columns small-centered large-uncentered">

     <% @not_completed_issues.each do |issue| %>
     <article class="event">

       <div class="event-date">
         <p class="event-month"> <%= issue.created_at.strftime("%m/%d") %>  </p>
         <p class="event-day"> <%= issue.created_at.strftime("%I:%M %p") %></p>
       </div>

       <div class="event-desc">
         <p class="event-desc-header"><%= link_to issue.headline, issue_path(issue) %></p>
       </div>

      </article>
       <hr>
    <% end %>

   </div>
 </div>

app/views/issues/new.html.erb
<div class="new-issue-page">
  <h4 class="title-issue-form">What's wrong with the bicycle?</h4>

<div id="out"></div>

<%= form_for @issue do |f| %>

  <%= f.label "headline", class: "issue-form-labels" %><br>
  <div class="issue-form-headline">
    <%= f.text_field :headline %>
  </div>

  <%= f.label "description", class: "issue-form-labels" %><br>
  <div class="issue-form-description">
    <%= f.text_field :description %>
  </div>

  <%= f.submit "Add Issue", class: "submit" %>

<% end %>
</div>

app/views/issues/show.html.erb
<h2> <%= @issue.headline %> </h2>
<h3> <%= @issue.description  %> </h3>


<div class="show_map">
  <div class="panel" id="map"></div>
</div>

<div class="delete-edit">
  <% if current_user.try(:admin?) %>
    <%= button_to 'Delete Issue', issue_path, method: :delete, class: "delete-edit" %>
    <%= button_to 'Edit', edit_issue_path(@issue), method: :get, class: "delete-edit" %>
  <% end %>

  <% if current_user == @issue.user %>
    <%= form_for @issue do |f| %>

      <%= f.text_field :completed, value: "true", type: "hidden" %>

      <%= f.submit "Completed?"%>

    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbb</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <script src="https://maps.googleapis.com/maps/api/js" type="text/javascript"></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>
  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name show-for-small">
      <h1><%= link_to 'BBB', root_path%></h1>
    </li>
    <li class="name hide-for-small">
      <h1><%= link_to 'Bicycles Benefit Boston', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path%></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
    </ul>
  </section>
</nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
  <script>
     $(document).ready(function() {
       setTimeout(function(){
         $(".flash").fadeOut("slow", function() {
           $(this).remove();
         })
       }, 3000);
     });
   </script>
</body>
</html>